import {StyleSheet} from 'react-native';
import {getThemeColor} from '../ThemeProvider/redux/saga';

export const getStyles = theme =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: getThemeColor('primary', theme),
    },
    header: {
      backgroundColor: getThemeColor('headerColor', theme),
      height: 72,
      gap: 10,
      borderBottomWidth: 1,
      borderBottomColor: getThemeColor('border', theme),
      paddingHorizontal: 20,
      alignItems: 'flex-end',
      paddingBottom: 16,
      flexDirection: 'row',
    },
    searchContainer: {
      width: '85%',
      height: 44,
      borderRadius: 22,
      marginLeft: 10,
    },
    imageDiv: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerText: {
      color: getThemeColor('headerText', theme),
      fontSize: 18,
      fontWeight: '600',
    },
    imgText: {
      color: getThemeColor('white', theme),
      fontSize: 16,
      fontWeight: '600',
      alignSelf: 'center',
    },
    userName: {
      color: getThemeColor('headerText', theme),
      fontSize: 17,
      fontWeight: '600',
      alignSelf: 'center',
    },
    sentTextHeader: {
      paddingTop: 8,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
    },
    sentHeaderView: {
      justifyContent: 'flex-end',
      marginLeft: 20,
      borderRadius: 16,
      marginBottom: 10,
      maxWidth: '65%',
      alignItems: 'flex-end',
    },
    sentText: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      color: getThemeColor('text', theme),
      fontSize: 14,
      fontWeight: '400',
      flexWrap: 'wrap',
    },
    imageContainer: {
      backgroundColor: getThemeColor('buttonColor', theme),
      width: 40,
      height: 40,
      marginHorizontal: 3,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    chatMainHeader: {
      marginHorizontal: 24,
    },
    composerRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    inputInnerContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      borderRadius: 24,
      marginHorizontal: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: getThemeColor('border', theme),
    },
    leftInputView: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    inputText: {
      fontSize: 15,
      minHeight: 44,
      flex: 1,
      paddingHorizontal: 4,
      color: getThemeColor('text', theme),
    },
    sendBtn: {
      backgroundColor: getThemeColor('buttonColor', theme),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 22,
      width: 44,
      height: 44,
    },
    childContainerStyle: {
      flex: 1,
      width: '100%',
    },
    listFlex: {
      flex: 1,
      width: '100%',
    },
    groupNameSection: {
      width: '100%',
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 8,
    },
    groupNameLabel: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      color: getThemeColor('text', theme),
    },
    groupNameInput: {
      width: '100%',
      height: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: getThemeColor('border', theme),
      backgroundColor: getThemeColor('inputBackground', theme),
      paddingHorizontal: 14,
      fontSize: 16,
      color: getThemeColor('text', theme),
    },
    helperText: {
      fontSize: 13,
      opacity: 0.75,
      color: getThemeColor('textSecondary', theme),
      textAlign: 'center',
      marginHorizontal: 20,
      marginBottom: 12,
    },
    selectedChipsRow: {
      width: '100%',
      paddingLeft: 20,
      paddingBottom: 8,
      maxHeight: 88,
    },
    selectedChip: {
      alignItems: 'center',
      marginRight: 12,
      width: 64,
    },
    selectedChipAvatar: {
      borderRadius: 8,
      width: 44,
      height: 44,
    },
    selectedChipRemove: {
      position: 'absolute',
      top: -4,
      right: -4,
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: getThemeColor('border', theme),
      zIndex: 2,
    },
    selectedChipName: {
      textAlign: 'center',
      fontSize: 11,
      marginTop: 4,
      color: getThemeColor('text', theme),
    },
    listHeaderBlock: {
      paddingHorizontal: 20,
      paddingTop: 4,
      paddingBottom: 8,
    },
    helperTextLeft: {
      fontSize: 13,
      opacity: 0.75,
      color: getThemeColor('textSecondary', theme),
      textAlign: 'left',
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: getThemeColor('text', theme),
      marginBottom: 8,
    },
    memberRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: getThemeColor('border', theme),
    },
    memberRowLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    memberAvatar: {
      borderRadius: 8,
      width: 48,
      height: 48,
      marginRight: 14,
    },
    memberName: {
      fontSize: 16,
      color: getThemeColor('text', theme),
      flex: 1,
    },
    emptyList: {
      paddingVertical: 40,
      alignItems: 'center',
    },
    emptyListText: {
      color: getThemeColor('textSecondary', theme),
      fontSize: 15,
    },
    bottomBar: {
      width: '100%',
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 16,
      borderTopWidth: 1,
      borderTopColor: getThemeColor('border', theme),
      backgroundColor: getThemeColor('primary', theme),
    },
    selectionCount: {
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 8,
      color: getThemeColor('textSecondary', theme),
    },
    backButtonHit: {
      justifyContent: 'center',
      height: 45,
    },
    listContent: {
      paddingBottom: 12,
      flexGrow: 1,
    },
    buttonDisabledOpacity: {
      opacity: 0.5,
    },
  });
